"""initial baseline

Revision ID: e615d4ffbbfb
Revises: 
Create Date: 2025-10-07 23:40:54.357468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e615d4ffbbfb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leave_balances', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_leave_balances_employee_id', table_name='leave_balances')
    op.create_foreign_key(None, 'leave_balances', 'employees', ['employee_id'], ['id'])
    op.alter_column('leaves', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_leaves_employee_id', table_name='leaves')
    op.create_foreign_key(None, 'leaves', 'employees', ['employee_id'], ['id'])
    op.alter_column('payroll_entries', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_payroll_entries_employee_id', table_name='payroll_entries')
    op.create_foreign_key(None, 'payroll_entries', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payroll_entries', type_='foreignkey')
    op.create_index('ix_payroll_entries_employee_id', 'payroll_entries', ['employee_id'], unique=False)
    op.alter_column('payroll_entries', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'leaves', type_='foreignkey')
    op.create_index('ix_leaves_employee_id', 'leaves', ['employee_id'], unique=False)
    op.alter_column('leaves', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'leave_balances', type_='foreignkey')
    op.create_index('ix_leave_balances_employee_id', 'leave_balances', ['employee_id'], unique=True)
    op.alter_column('leave_balances', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
