"""Created TaxConfig and BenefitConfig table, add allowances attribute to EmployeeDB & PayrollDB

Revision ID: febc9e6ce061
Revises: ac279a21b4db
Create Date: 2025-10-09 14:30:24.892162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'febc9e6ce061'
down_revision: Union[str, None] = 'ac279a21b4db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tax_config_tax_type', table_name='tax_config')
    op.drop_index('ix_tax_config_year', table_name='tax_config')
    op.drop_table('tax_config')
    op.add_column('employees', sa.Column('allowances', sa.JSON(), nullable=True))
    op.add_column('payroll_entries', sa.Column('allowances', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payroll_entries', 'allowances')
    op.drop_column('employees', 'allowances')
    op.create_table('tax_config',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tax_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('tax_brackets', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tax_config_pkey')
    )
    op.create_index('ix_tax_config_year', 'tax_config', ['year'], unique=False)
    op.create_index('ix_tax_config_tax_type', 'tax_config', ['tax_type'], unique=False)
    # ### end Alembic commands ###
